name: 🔧 Installation Issue
description: Report problems with installation, setup, or connectivity
title: "[Install]: "
labels: ["installation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Before You Continue

        **Please try these resources first:**

        1. 📚 **[README Installation Guide](https://github.com/lfnovo/open-notebook#installation)** - Comprehensive setup instructions

        2. 🦙 **Ollama Issues?** Make sure Ollama is running: `ollama serve`

        3. 💬 **[Discord Community](https://discord.gg/37XJPXfz2w)** - Get real-time help from the community

        ---

        If you've tried the above and still need help, please fill out the form below with as much detail as possible.

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How are you trying to install Open Notebook?
      options:
        - pip install open-notebook
        - pip install -e . (local development)
        - uv pip install open-notebook
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: What is the issue?
      description: Describe the installation or setup problem you're experiencing
      placeholder: |
        Example: "I can't install the package" or "Getting import errors" or "Can't connect to SurrealDB"
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
        Please provide the full error message and stack trace. **This is very important for diagnosing issues!**

        **How to get logs:**
        - Copy the full Python traceback
        - Enable verbose output: `pip install -vvv open-notebook`
      placeholder: |
        Paste your error here. Include the full error message and stack trace if available.
      render: shell
    validations:
      required: false

  - type: textarea
    id: env-file
    attributes:
      label: Environment Configuration
      description: |
        If you're having database connection issues, please paste your environment variables here.

        **⚠️ IMPORTANT: REDACT ALL API KEYS AND PASSWORDS!**
      placeholder: |
        SURREAL_URL=ws://localhost:8000/rpc
        SURREAL_USER=root
        SURREAL_PASSWORD=***REDACTED***
        OPENAI_API_KEY=sk-***REDACTED***
      render: shell
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Tell us about your setup
      placeholder: |
        - Operating System: Ubuntu 22.04 / Windows 11 / macOS 14
        - Python version: `python --version`
        - pip version: `pip --version`
        - SurrealDB version: `surreal version`
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Are you behind a corporate proxy or firewall?
        - Are you using a VPN?
        - Are you using a virtual environment (venv, conda, etc.)?
        - Did this work before and suddenly break?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've tried these steps
      options:
        - label: I read the [README Installation Guide](https://github.com/lfnovo/open-notebook#installation)
          required: false
        - label: I searched existing issues to see if this was already reported
          required: true
        - label: I redacted all sensitive information (API keys, passwords, etc.)
          required: true
